name: Act_IPs_Imperva.txt

on:
  schedule:
    - cron: "*/720 * * * *"

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Ejecutar comando curl y actualizar archivo
        run: |
          curl -s --data "resp_format=text" https://my.imperva.com/api/integration/v1/ips > Dir_IPs_Actualizadas.txt
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@users.noreply.github.com"
          git add direcciones.txt
          git commit -m "Dir_IPs_Actualizadas.txt"
          git push
